version: 2
updates:
  - commit-message:
      prefix: "chore"
    directory: /backend-acceptance-testing
    package-ecosystem: docker
    schedule:
      interval: weekly
  - commit-message:
      prefix: "chore"
    directory: /backend-acceptance-testing
    package-ecosystem: pip
    schedule:
      interval: weekly
  - commit-message:
      prefix: "chore"
    directory: /backend-integration-testing
    package-ecosystem: docker
    schedule:
      interval: monthly
  - commit-message:
      prefix: "chore"
    directory: /backend-integration-testing
    package-ecosystem: pip
    schedule:
      interval: monthly
  - commit-message:
      prefix: "chore"
    directory: /gui-e2e-testing
    package-ecosystem: docker
    schedule:
      interval: monthly
  - commit-message:
      prefix: "chore"
    directory: /qa-acceptance-testing
    package-ecosystem: docker
    schedule:
      interval: weekly
  - commit-message:
      prefix: "chore"
    directory: /qa-acceptance-testing
    package-ecosystem: pip
    schedule:
      interval: weekly
  - commit-message:
      prefix: "chore"
    directory: /docker/docker-files-raspbian
    package-ecosystem: docker
    schedule:
      interval: weekly
