image: docker:git

variables:
  RASPBIAN_VERSION: '2019-07-10'
  DOCKER_REPOSITORY: 'mendersoftware/mender-test-containers'
  DOCKER_HUB_USERNAME: 'menderbuildsystem'

stages:
  - test
  - build_prep
  - build
  - publish

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-commits-signoffs.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-python3-format.yml'

build_prep:
  stage: build_prep
  needs: []
  image: buildpack-deps:scm
  script:
    - cd docker/docker-files-raspbian
    - apt-get update && apt-get install -yyq sudo unzip
    - ./prepare-raspbian-img.sh ${RASPBIAN_VERSION}
    - cd .. && tar -cvf $CI_PROJECT_DIR/docker-files-raspbian.tar docker-files-raspbian
  artifacts:
    expire_in: 2w
    paths:
      - docker-files-raspbian.tar
  tags:
    - mender-qa-slave

build:raspbian_latest:
  stage: build
  dependencies:
    - build_prep
  services:
    - docker:dind
  script:
    - tar -xvf docker-files-raspbian.tar
    - docker build --build-arg raspbian_version=${RASPBIAN_VERSION} -t $DOCKER_REPOSITORY:raspbian_latest docker-files-raspbian
    - docker save $DOCKER_REPOSITORY:raspbian_latest > raspbianImage.tar
  artifacts:
    expire_in: 2w
    paths:
      - raspbianImage.tar

build:acceptance-testing:
  stage: build
  needs: []
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_REPOSITORY:acceptance-testing -f backend-acceptance-testing/Dockerfile.backend-tests backend-acceptance-testing
    - docker save $DOCKER_REPOSITORY:acceptance-testing > acceptanceTestingImage.tar
  artifacts:
    expire_in: 2w
    paths:
      - acceptanceTestingImage.tar

build:mender-client-acceptance-testing:
  stage: build
  needs: []
  tags:
    - mender-qa-slave-highcpu
  services:
    - docker:dind
  before_script:
    - export AWS_ACCESS_KEY_ID=$TMP_STORAGE_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$TMP_STORAGE_AWS_SECRET_ACCESS_KEY
    - apk --update add aws-cli
  script:
    - docker build -t $DOCKER_REPOSITORY:mender-client-acceptance-testing -f mender-client-acceptance-testing/Dockerfile mender-client-acceptance-testing
    - docker save $DOCKER_REPOSITORY:mender-client-acceptance-testing > qaTestingImage.tar
    # Artifact is too large for GitLab, save in temporary S3 bucket
    - aws s3 cp qaTestingImage.tar s3://mender-gitlab-tmp-storage/$CI_PROJECT_NAME/$CI_PIPELINE_ID/qaTestingImage.tar

publish:build:master:
  stage: publish
  dependencies:
    - build:raspbian_latest
    - build:acceptance-testing
    - build:mender-client-acceptance-testing
  services:
    - docker:dind
  before_script:
    - export AWS_ACCESS_KEY_ID=$TMP_STORAGE_AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$TMP_STORAGE_AWS_SECRET_ACCESS_KEY
    - apk --update add aws-cli
  script:
    - echo "publishing images to Docker Hub"
    - echo -n $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    - docker load -i raspbianImage.tar
    - docker push $DOCKER_REPOSITORY:raspbian_latest;
    - docker load -i acceptanceTestingImage.tar
    - docker push $DOCKER_REPOSITORY:acceptance-testing
    # Fetch from temporary S3 bucket
    - aws s3 cp s3://mender-gitlab-tmp-storage/$CI_PROJECT_NAME/$CI_PIPELINE_ID/qaTestingImage.tar qaTestingImage.tar
    - docker load -i qaTestingImage.tar
    - docker push $DOCKER_REPOSITORY:mender-client-acceptance-testing
  only:
    - master
  tags:
    - docker
