image: docker:git

variables:
  RASPBIAN_VERSION: '2019-07-10'
  DOCKER_REPOSITORY: 'mendersoftware/mender-test-containers'
  DOCKER_HUB_USERNAME: 'menderbuildsystem'
  DOCKER_BUILDKIT: 1

stages:
  - test
  - build_prep
  - build
  - publish

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-commits-signoffs.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-python3-format.yml'

build_prep:
  stage: build_prep
  needs: []
  image: buildpack-deps:scm
  script:
    - cd docker/docker-files-raspbian
    - apt-get update && apt-get install -yyq sudo unzip fdisk
    - ./prepare-raspbian-img.sh ${RASPBIAN_VERSION}
    - cd .. && tar -cvf $CI_PROJECT_DIR/docker-files-raspbian.tar docker-files-raspbian
  artifacts:
    expire_in: 2w
    paths:
      - docker-files-raspbian.tar

build:raspbian_latest:
  stage: build
  dependencies:
    - build_prep
  services:
    - docker:dind
  script:
    - tar -xvf docker-files-raspbian.tar
    - docker build --build-arg raspbian_version=${RASPBIAN_VERSION} -t $DOCKER_REPOSITORY:raspbian_latest docker-files-raspbian
    - docker save $DOCKER_REPOSITORY:raspbian_latest > raspbianImage.tar
  artifacts:
    expire_in: 2w
    paths:
      - raspbianImage.tar

build:acceptance-testing:
  stage: build
  needs: []
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_REPOSITORY:acceptance-testing -f backend-acceptance-testing/Dockerfile.backend-tests backend-acceptance-testing
    - docker save $DOCKER_REPOSITORY:acceptance-testing > acceptanceTestingImage.tar
  artifacts:
    expire_in: 2w
    paths:
      - acceptanceTestingImage.tar

build:gui-e2e-testing:
  stage: build
  needs: []
  services:
    - docker:dind
  before_script:
    - apk add --no-cache aws-cli curl
    - eval "$(curl https://raw.githubusercontent.com/mendersoftware/mendertesting/master/mender-ci-common.sh)"
  script:
    - docker build -t $DOCKER_REPOSITORY:gui-e2e-testing -f gui-e2e-testing/Dockerfile gui-e2e-testing
    - docker save $DOCKER_REPOSITORY:gui-e2e-testing > guiE2eTestingImage.tar
    # Upload to temporary S3 bucket
    - mender_ci_save_tmp_artifact guiE2eTestingImage.tar
  artifacts:
    paths:
      - checksums

build:backend-integration-testing:
  stage: build
  needs: []
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_REPOSITORY:backend-integration-testing -f backend-integration-testing/Dockerfile backend-integration-testing
    - docker save $DOCKER_REPOSITORY:backend-integration-testing > integrationTestingImage.tar
  artifacts:
    expire_in: 2w
    paths:
      - integrationTestingImage.tar

build:mender-client-acceptance-testing:
  stage: build
  needs: []
  tags:
    # KVM support requires the same type of GCP machine as the tests will use
    - mender-qa-worker-client-acceptance-tests
  services:
    - docker:dind
  before_script:
    - apk add --no-cache aws-cli curl
    - eval "$(curl https://raw.githubusercontent.com/mendersoftware/mendertesting/master/mender-ci-common.sh)"
  script:
    - docker build -t $DOCKER_REPOSITORY:mender-client-acceptance-testing -f mender-client-acceptance-testing/Dockerfile mender-client-acceptance-testing
    - docker save $DOCKER_REPOSITORY:mender-client-acceptance-testing > qaTestingImage.tar
    # Upload to temporary S3 bucket
    - mender_ci_save_tmp_artifact qaTestingImage.tar
  artifacts:
    paths:
      - checksums

.template:publish:
  stage: publish
  services:
    - docker:dind
  only:
    - master
  tags:
    - docker
  before_script:
    - echo -n $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin

publish:raspbian_latest:
  extends: .template:publish
  dependencies:
    - build:raspbian_latest
  script:
    - echo "publishing image to Docker Hub"
    - docker load -i raspbianImage.tar
    - docker push $DOCKER_REPOSITORY:raspbian_latest

publish:acceptance-testing:
  extends: .template:publish
  dependencies:
    - build:acceptance-testing
  script:
    - echo "publishing image to Docker Hub"
    - docker load -i acceptanceTestingImage.tar
    - docker push $DOCKER_REPOSITORY:acceptance-testing

publish:backend-integration-testing:
  extends: .template:publish
  dependencies:
    - build:backend-integration-testing
  script:
    - echo "publishing image to Docker Hub"
    - docker load -i integrationTestingImage.tar
    - docker push $DOCKER_REPOSITORY:backend-integration-testing

publish:gui-e2e-testing:
  extends: .template:publish
  dependencies:
    - build:gui-e2e-testing
  script:
    - apk add --no-cache aws-cli curl
    - eval "$(curl https://raw.githubusercontent.com/mendersoftware/mendertesting/master/mender-ci-common.sh)"
    # Fetch from temporary S3 bucket
    - mender_ci_load_tmp_artifact guiE2eTestingImage.tar
    - echo "publishing image to Docker Hub"
    - docker load -i guiE2eTestingImage.tar
    - docker push $DOCKER_REPOSITORY:gui-e2e-testing

publish:mender-client-acceptance-testing:
  extends: .template:publish
  dependencies:
    - build:mender-client-acceptance-testing
  script:
    - apk add --no-cache aws-cli curl
    - eval "$(curl https://raw.githubusercontent.com/mendersoftware/mendertesting/master/mender-ci-common.sh)"
    # Fetch from temporary S3 bucket
    - mender_ci_load_tmp_artifact qaTestingImage.tar
    - echo "publishing image to Docker Hub"
    - docker load -i qaTestingImage.tar
    - docker push $DOCKER_REPOSITORY:mender-client-acceptance-testing
